# 项目相关配置
ruoyi:
  # 名称
  name: 乡村振兴驿站
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径
  # Windows配置
  profile: I:/Workspace/Java/village-station/uploadPath
  # Linux配置
  # profile: /home/village-station/backend/profileUploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# Spring配置
spring:
  profiles:
    active: dev